<%@ LANGUAGE = VBScript.Encode %>
<!--#include file="aspcs.asp"-->

<!--#include file="you.asp"-->
<!--#include file="conn.asp"-->
<!--#include file="zcm.asp"-->
<!--#include file="admin.ASP"-->
<!--#include file="Inc/articlechar.inc"-->
<%#@~^NQcAAA==@#@&@#@&GksPqG~tG4mxS?$VS]k~sK;x9+DM@#@&sKE	+.DxomVd+@#@&q6PP.b:`]n$En/D wW.s`rHW(l	E#*'EJ,K4n	@#@&wGE	N+M.xKME@#@&2..s/L'A.Ds/LQr@!Vr@*模板内容不能为空@!zsk@*E@#@&3	N,q0@#@&&WPwW;x9+..{sl^d+,KtU@#@&tW(lU']n$En/DcJtW8C	J#@#@&U+OP"d{?nM\DR;DCYW8LmOcrbNK[4cI+1G.Nk+DJb@#@&(6P]+$;+kYcEmmYrG	Jb'r39kOtW(lxrP:4+	@#@&VNmhdc/l7n:K`#@#@&3x9P&0@#@&@#@&U+OP"d'	WO4bxo@#@&;WUxc/^Wd@#@&?+DP;Gx	'UWDtrUT@#@&"n/aWxkn MkD+~J@!uD:s@*r@#@&"+d2Kx/n qDrY~r@!ul9@*J@#@&"n/aWU/R	.bY+,E@!:kY^n@*管理中心@!JYbYs+@*E@#@&]+k2W	/n qDkOn,J@!HOmPuDYaO2$Eb-'rJ/W	YnUDOKH2+rJP;GUYxD'EJPnXY&CDhVpP/4mD?nO{M8 2qyJE@*J@#@&I/aGxk+ MkOn,J@!UOX^+@*r@#@&I/aWU/n qDrY~JDN`WKxYRdbyn)O2DisbxOtkT4Y=F*!u8E@#@&I+k2W	/+c	.kD+,J8W[zP0GxDR/bynlOwYIsbxnO4nbo4D)8c!u8r@#@&"+dwKxdncDbO+,Jl=srx0P,P~P~~PP^W^GD=P:TZ&&//pPO+XO Nn1WMlYbW	lP	WU+,8E@#@&I+k2W	/+c	.kD+,JC)-rkkO+9~P,P`~1WVG.=P:!Zf2Z/pPD+6DO9nmKDCYbWUl,xW	nP)J@#@&]n/aW	/nR	.bYnPrC)mmOr7+P~~,P`P1G^W.=P[ssZ!ZTi,Yn6DO[n1WDmOkKx),UGxP)J@#@&]nkwGxknRqDrOPJCl4W-+M~,P~,PPPmKVK.),aT!Z!TTpPYaY N+1G.lDkKxlP;U9+.VbU+)J@#@&"+/2G	/nRq.bYn,J@!z/DX^n@*r@#@&I/2G	/+c	DbY+,E@!z_+mN@*J@#@&"+dwKU/R	.bY+~E@!4GNH~DW2slMok	'rEvrJ~V0OhmDobU'rJ!rE@*J@#@&"+dwGUk+ MrYPE@!aPlsrTxxJr^xODrJ@*r@#@&]+kwGxk+ 	MkY~J@!Yl(snP(WMNnDxEr!EJ,^+^V2C9NkUL{JE!rE,mn^Vkwl1k	L'rJTJrPAr9Yt{EJ8!!uEE@*r@#@&qWP]n$En/DcJmmOrKxJbxmN[HK8mx~:tx@#@&IdwKxd+c.rD+Pr@!YM@*J@#@&]+kwKxd+ 	MkO+,E@!DN~AbNY4xrJq!ZYrJ@*·@!0KxY,mKsWM'EJ[soTZ!!rE@*@!4@*添加修改e@!&4@*@!J0GxO@*@!zON@*E@#@&IndaWxdnc.kDn,J@!JYM@*J@#@&As/@#@&I/2G	/+c	DbY+,E@!YM@*r@#@&IndaWU/ MkOn,J@!O[,hrND4{JE8!Z]Jr@*·@!WW	Y~mKVG.{JJ[osZ!!ZEE@*@!4@*成功：模板已经修改成功"@!z8@*@!zWW	O@*@!zO[@*J@#@&]/2W	dR	MkD+Pr@!JOD@*J@#@&Ax[~&0@#@&]+kwW	dnRqDbYnPE@!JYC4^n@*r@#@&]/wGUk+ MrD+~r@!J4W9X@*E@#@&In/aWUdRMrYPJ@!&4YsV@*J@#@&3sk+@#@&"n/aWUdR.rD+~J由于以下的原因不能保存数据：r@#@&InkwKx/Rq.kD+~2MDhdT@#@&AHf,qs@#@&@#@&,ZwUCAA==^#~@%>
